//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WeatherForecast
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Area.
    /// </summary>
    // *** Start programmer edit section *** (Area CustomAttributes)

    // *** End programmer edit section *** (Area CustomAttributes)
    [BusinessServer("IIS.WeatherForecast.ArchiverBS, WeatherForecast.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnDeleteFromStorage)]
    [AutoAltered()]
    [Caption("Местность")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AreaE", new string[] {
            "Id as \'Идентификатор\'",
            "Name as \'Наименование\'",
            "IsArchive as \'Архивный\'",
            "Region as \'Регион\'",
            "Region.Name as \'Наименование региона\'"}, Hidden=new string[] {
            "Region.Name"})]
    [MasterViewDefineAttribute("AreaE", "Region", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("AreaL", new string[] {
            "Id as \'Идентификатор\'",
            "Name as \'Наименование\'",
            "IsArchive as \'Архивный\'",
            "Region.Name as \'Регион\'"}, Hidden=new string[] {
            "IsArchive"})]
    public class Area : ICSSoft.STORMNET.DataObject
    {
        
        private int fId;
        
        private string fName;
        
        private bool fIsArchive;
        
        private IIS.WeatherForecast.Region fRegion;
        
        // *** Start programmer edit section *** (Area CustomMembers)

        // *** End programmer edit section *** (Area CustomMembers)

        
        /// <summary>
        /// Id.
        /// </summary>
        // *** Start programmer edit section *** (Area.Id CustomAttributes)

        // *** End programmer edit section *** (Area.Id CustomAttributes)
        public virtual int Id
        {
            get
            {
                // *** Start programmer edit section *** (Area.Id Get start)

                // *** End programmer edit section *** (Area.Id Get start)
                int result = this.fId;
                // *** Start programmer edit section *** (Area.Id Get end)

                // *** End programmer edit section *** (Area.Id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Area.Id Set start)

                // *** End programmer edit section *** (Area.Id Set start)
                this.fId = value;
                // *** Start programmer edit section *** (Area.Id Set end)

                // *** End programmer edit section *** (Area.Id Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Area.Name CustomAttributes)

        // *** End programmer edit section *** (Area.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Area.Name Get start)

                // *** End programmer edit section *** (Area.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Area.Name Get end)

                // *** End programmer edit section *** (Area.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Area.Name Set start)

                // *** End programmer edit section *** (Area.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Area.Name Set end)

                // *** End programmer edit section *** (Area.Name Set end)
            }
        }
        
        /// <summary>
        /// IsArchive.
        /// </summary>
        // *** Start programmer edit section *** (Area.IsArchive CustomAttributes)

        // *** End programmer edit section *** (Area.IsArchive CustomAttributes)
        public virtual bool IsArchive
        {
            get
            {
                // *** Start programmer edit section *** (Area.IsArchive Get start)

                // *** End programmer edit section *** (Area.IsArchive Get start)
                bool result = this.fIsArchive;
                // *** Start programmer edit section *** (Area.IsArchive Get end)

                // *** End programmer edit section *** (Area.IsArchive Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Area.IsArchive Set start)

                // *** End programmer edit section *** (Area.IsArchive Set start)
                this.fIsArchive = value;
                // *** Start programmer edit section *** (Area.IsArchive Set end)

                // *** End programmer edit section *** (Area.IsArchive Set end)
            }
        }
        
        /// <summary>
        /// Area.
        /// </summary>
        // *** Start programmer edit section *** (Area.Region CustomAttributes)

        // *** End programmer edit section *** (Area.Region CustomAttributes)
        [PropertyStorage(new string[] {
                "Region"})]
        [NotNull()]
        public virtual IIS.WeatherForecast.Region Region
        {
            get
            {
                // *** Start programmer edit section *** (Area.Region Get start)

                // *** End programmer edit section *** (Area.Region Get start)
                IIS.WeatherForecast.Region result = this.fRegion;
                // *** Start programmer edit section *** (Area.Region Get end)

                // *** End programmer edit section *** (Area.Region Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Area.Region Set start)

                // *** End programmer edit section *** (Area.Region Set start)
                this.fRegion = value;
                // *** Start programmer edit section *** (Area.Region Set end)

                // *** End programmer edit section *** (Area.Region Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AreaE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AreaE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AreaE", typeof(IIS.WeatherForecast.Area));
                }
            }
            
            /// <summary>
            /// "AreaL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AreaL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AreaL", typeof(IIS.WeatherForecast.Area));
                }
            }
        }
    }
}
