//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WeatherForecast
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Cataclysm.
    /// </summary>
    // *** Start programmer edit section *** (Cataclysm CustomAttributes)

    // *** End programmer edit section *** (Cataclysm CustomAttributes)
    [AutoAltered()]
    [Caption("Природный катаклизм")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CataclysmE", new string[] {
            "Name as \'Наименование\'"})]
    [View("CataclysmL", new string[] {
            "Name as \'Наименование\'"})]
    public class Cataclysm : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Cataclysm CustomMembers)

        // *** End programmer edit section *** (Cataclysm CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Cataclysm.Name CustomAttributes)

        // *** End programmer edit section *** (Cataclysm.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Cataclysm.Name Get start)

                // *** End programmer edit section *** (Cataclysm.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Cataclysm.Name Get end)

                // *** End programmer edit section *** (Cataclysm.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Cataclysm.Name Set start)

                // *** End programmer edit section *** (Cataclysm.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Cataclysm.Name Set end)

                // *** End programmer edit section *** (Cataclysm.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CataclysmE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CataclysmE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CataclysmE", typeof(IIS.WeatherForecast.Cataclysm));
                }
            }
            
            /// <summary>
            /// "CataclysmL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CataclysmL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CataclysmL", typeof(IIS.WeatherForecast.Cataclysm));
                }
            }
        }
    }
}
