//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WeatherForecast
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Overcast.
    /// </summary>
    // *** Start programmer edit section *** (Overcast CustomAttributes)

    // *** End programmer edit section *** (Overcast CustomAttributes)
    [AutoAltered()]
    [Caption("Облачность")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("OvercastE", new string[] {
            "Name as \'Наименование\'"})]
    [View("OvercastL", new string[] {
            "Name as \'Наименование\'"})]
    public class Overcast : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Overcast CustomMembers)

        // *** End programmer edit section *** (Overcast CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Overcast.Name CustomAttributes)

        // *** End programmer edit section *** (Overcast.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Overcast.Name Get start)

                // *** End programmer edit section *** (Overcast.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Overcast.Name Get end)

                // *** End programmer edit section *** (Overcast.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Overcast.Name Set start)

                // *** End programmer edit section *** (Overcast.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Overcast.Name Set end)

                // *** End programmer edit section *** (Overcast.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "OvercastE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OvercastE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OvercastE", typeof(IIS.WeatherForecast.Overcast));
                }
            }
            
            /// <summary>
            /// "OvercastL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View OvercastL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("OvercastL", typeof(IIS.WeatherForecast.Overcast));
                }
            }
        }
    }
}
