//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WeatherForecast
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Possible cataclysm.
    /// </summary>
    // *** Start programmer edit section *** (PossibleCataclysm CustomAttributes)

    // *** End programmer edit section *** (PossibleCataclysm CustomAttributes)
    [BusinessServer("IIS.WeatherForecast.ArchiverBS, WeatherForecast.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnDeleteFromStorage)]
    [AutoAltered()]
    [Caption("Возможный катаклизм")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PossibleCataclysmE", new string[] {
            "Cataclysm as \'Катаклизм\'",
            "Cataclysm.Name as \'Name\'",
            "Start as \'Начало катаклизма\'",
            "Finish as \'Конец катаклизма\'",
            "IsArchive as \'Архивный\'"}, Hidden=new string[] {
            "Cataclysm.Name",
            "IsArchive"})]
    [MasterViewDefineAttribute("PossibleCataclysmE", "Cataclysm", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "Name")]
    [View("PossibleCataclysmL", new string[] {
            "Cataclysm.Name as \'Катаклизм\'",
            "Start as \'Начало катаклизма\'",
            "Finish as \'Конец катаклизма\'",
            "IsArchive as \'Архивный\'"}, Hidden=new string[] {
            "IsArchive"})]
    public class PossibleCataclysm : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fStart;
        
        private System.DateTime fFinish;
        
        private bool fIsArchive;
        
        private IIS.WeatherForecast.Cataclysm fCataclysm;
        
        private IIS.WeatherForecast.DayForecast fDayForecast;
        
        // *** Start programmer edit section *** (PossibleCataclysm CustomMembers)

        // *** End programmer edit section *** (PossibleCataclysm CustomMembers)

        
        /// <summary>
        /// Start.
        /// </summary>
        // *** Start programmer edit section *** (PossibleCataclysm.Start CustomAttributes)

        // *** End programmer edit section *** (PossibleCataclysm.Start CustomAttributes)
        public virtual System.DateTime Start
        {
            get
            {
                // *** Start programmer edit section *** (PossibleCataclysm.Start Get start)

                // *** End programmer edit section *** (PossibleCataclysm.Start Get start)
                System.DateTime result = this.fStart;
                // *** Start programmer edit section *** (PossibleCataclysm.Start Get end)

                // *** End programmer edit section *** (PossibleCataclysm.Start Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PossibleCataclysm.Start Set start)

                // *** End programmer edit section *** (PossibleCataclysm.Start Set start)
                this.fStart = value;
                // *** Start programmer edit section *** (PossibleCataclysm.Start Set end)

                // *** End programmer edit section *** (PossibleCataclysm.Start Set end)
            }
        }
        
        /// <summary>
        /// Finish.
        /// </summary>
        // *** Start programmer edit section *** (PossibleCataclysm.Finish CustomAttributes)

        // *** End programmer edit section *** (PossibleCataclysm.Finish CustomAttributes)
        public virtual System.DateTime Finish
        {
            get
            {
                // *** Start programmer edit section *** (PossibleCataclysm.Finish Get start)

                // *** End programmer edit section *** (PossibleCataclysm.Finish Get start)
                System.DateTime result = this.fFinish;
                // *** Start programmer edit section *** (PossibleCataclysm.Finish Get end)

                // *** End programmer edit section *** (PossibleCataclysm.Finish Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PossibleCataclysm.Finish Set start)

                // *** End programmer edit section *** (PossibleCataclysm.Finish Set start)
                this.fFinish = value;
                // *** Start programmer edit section *** (PossibleCataclysm.Finish Set end)

                // *** End programmer edit section *** (PossibleCataclysm.Finish Set end)
            }
        }
        
        /// <summary>
        /// IsArchive.
        /// </summary>
        // *** Start programmer edit section *** (PossibleCataclysm.IsArchive CustomAttributes)

        // *** End programmer edit section *** (PossibleCataclysm.IsArchive CustomAttributes)
        public virtual bool IsArchive
        {
            get
            {
                // *** Start programmer edit section *** (PossibleCataclysm.IsArchive Get start)

                // *** End programmer edit section *** (PossibleCataclysm.IsArchive Get start)
                bool result = this.fIsArchive;
                // *** Start programmer edit section *** (PossibleCataclysm.IsArchive Get end)

                // *** End programmer edit section *** (PossibleCataclysm.IsArchive Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PossibleCataclysm.IsArchive Set start)

                // *** End programmer edit section *** (PossibleCataclysm.IsArchive Set start)
                this.fIsArchive = value;
                // *** Start programmer edit section *** (PossibleCataclysm.IsArchive Set end)

                // *** End programmer edit section *** (PossibleCataclysm.IsArchive Set end)
            }
        }
        
        /// <summary>
        /// Possible cataclysm.
        /// </summary>
        // *** Start programmer edit section *** (PossibleCataclysm.Cataclysm CustomAttributes)

        // *** End programmer edit section *** (PossibleCataclysm.Cataclysm CustomAttributes)
        [PropertyStorage(new string[] {
                "Cataclysm"})]
        [NotNull()]
        public virtual IIS.WeatherForecast.Cataclysm Cataclysm
        {
            get
            {
                // *** Start programmer edit section *** (PossibleCataclysm.Cataclysm Get start)

                // *** End programmer edit section *** (PossibleCataclysm.Cataclysm Get start)
                IIS.WeatherForecast.Cataclysm result = this.fCataclysm;
                // *** Start programmer edit section *** (PossibleCataclysm.Cataclysm Get end)

                // *** End programmer edit section *** (PossibleCataclysm.Cataclysm Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PossibleCataclysm.Cataclysm Set start)

                // *** End programmer edit section *** (PossibleCataclysm.Cataclysm Set start)
                this.fCataclysm = value;
                // *** Start programmer edit section *** (PossibleCataclysm.Cataclysm Set end)

                // *** End programmer edit section *** (PossibleCataclysm.Cataclysm Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.WeatherForecast.DayForecast.
        /// </summary>
        // *** Start programmer edit section *** (PossibleCataclysm.DayForecast CustomAttributes)

        // *** End programmer edit section *** (PossibleCataclysm.DayForecast CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "DayForecast"})]
        public virtual IIS.WeatherForecast.DayForecast DayForecast
        {
            get
            {
                // *** Start programmer edit section *** (PossibleCataclysm.DayForecast Get start)

                // *** End programmer edit section *** (PossibleCataclysm.DayForecast Get start)
                IIS.WeatherForecast.DayForecast result = this.fDayForecast;
                // *** Start programmer edit section *** (PossibleCataclysm.DayForecast Get end)

                // *** End programmer edit section *** (PossibleCataclysm.DayForecast Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (PossibleCataclysm.DayForecast Set start)

                // *** End programmer edit section *** (PossibleCataclysm.DayForecast Set start)
                this.fDayForecast = value;
                // *** Start programmer edit section *** (PossibleCataclysm.DayForecast Set end)

                // *** End programmer edit section *** (PossibleCataclysm.DayForecast Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PossibleCataclysmE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PossibleCataclysmE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PossibleCataclysmE", typeof(IIS.WeatherForecast.PossibleCataclysm));
                }
            }
            
            /// <summary>
            /// "PossibleCataclysmL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PossibleCataclysmL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PossibleCataclysmL", typeof(IIS.WeatherForecast.PossibleCataclysm));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of PossibleCataclysm.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfPossibleCataclysm CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfPossibleCataclysm CustomAttributes)
    public class DetailArrayOfPossibleCataclysm : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.WeatherForecast.DetailArrayOfPossibleCataclysm members)

        // *** End programmer edit section *** (IIS.WeatherForecast.DetailArrayOfPossibleCataclysm members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type PossibleCataclysm by index.
        /// </summary>
        /// <summary>
        /// Adds object with type PossibleCataclysm.
        /// </summary>
        public DetailArrayOfPossibleCataclysm(IIS.WeatherForecast.DayForecast fDayForecast) : 
                base(typeof(PossibleCataclysm), ((ICSSoft.STORMNET.DataObject)(fDayForecast)))
        {
        }
        
        public IIS.WeatherForecast.PossibleCataclysm this[int index]
        {
            get
            {
                return ((IIS.WeatherForecast.PossibleCataclysm)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.WeatherForecast.PossibleCataclysm dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
