//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WeatherForecast
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Region.
    /// </summary>
    // *** Start programmer edit section *** (Region CustomAttributes)

    // *** End programmer edit section *** (Region CustomAttributes)
    [BusinessServer("IIS.WeatherForecast.ArchiverBS, WeatherForecast.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnDeleteFromStorage)]
    [AutoAltered()]
    [Caption("Регион")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RegionE", new string[] {
            "Id as \'Идентификатор\'",
            "Name as \'Наименование\'",
            "IsArchive as \'Архивный\'"}, Hidden=new string[] {
            "IsArchive"})]
    [View("RegionL", new string[] {
            "Id as \'Идентификатор\'",
            "Name as \'Наименование\'",
            "IsArchive as \'Архивный\'"}, Hidden=new string[] {
            "IsArchive"})]
    public class Region : ICSSoft.STORMNET.DataObject
    {
        
        private int fId;
        
        private string fName;
        
        private bool fIsArchive;
        
        // *** Start programmer edit section *** (Region CustomMembers)

        // *** End programmer edit section *** (Region CustomMembers)

        
        /// <summary>
        /// Id.
        /// </summary>
        // *** Start programmer edit section *** (Region.Id CustomAttributes)

        // *** End programmer edit section *** (Region.Id CustomAttributes)
        public virtual int Id
        {
            get
            {
                // *** Start programmer edit section *** (Region.Id Get start)

                // *** End programmer edit section *** (Region.Id Get start)
                int result = this.fId;
                // *** Start programmer edit section *** (Region.Id Get end)

                // *** End programmer edit section *** (Region.Id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Region.Id Set start)

                // *** End programmer edit section *** (Region.Id Set start)
                this.fId = value;
                // *** Start programmer edit section *** (Region.Id Set end)

                // *** End programmer edit section *** (Region.Id Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Region.Name CustomAttributes)

        // *** End programmer edit section *** (Region.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Region.Name Get start)

                // *** End programmer edit section *** (Region.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Region.Name Get end)

                // *** End programmer edit section *** (Region.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Region.Name Set start)

                // *** End programmer edit section *** (Region.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Region.Name Set end)

                // *** End programmer edit section *** (Region.Name Set end)
            }
        }
        
        /// <summary>
        /// IsArchive.
        /// </summary>
        // *** Start programmer edit section *** (Region.IsArchive CustomAttributes)

        // *** End programmer edit section *** (Region.IsArchive CustomAttributes)
        public virtual bool IsArchive
        {
            get
            {
                // *** Start programmer edit section *** (Region.IsArchive Get start)

                // *** End programmer edit section *** (Region.IsArchive Get start)
                bool result = this.fIsArchive;
                // *** Start programmer edit section *** (Region.IsArchive Get end)

                // *** End programmer edit section *** (Region.IsArchive Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Region.IsArchive Set start)

                // *** End programmer edit section *** (Region.IsArchive Set start)
                this.fIsArchive = value;
                // *** Start programmer edit section *** (Region.IsArchive Set end)

                // *** End programmer edit section *** (Region.IsArchive Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RegionE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RegionE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RegionE", typeof(IIS.WeatherForecast.Region));
                }
            }
            
            /// <summary>
            /// "RegionL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RegionL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RegionL", typeof(IIS.WeatherForecast.Region));
                }
            }
        }
    }
}
