//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WeatherForecast
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Subscription.
    /// </summary>
    // *** Start programmer edit section *** (Subscription CustomAttributes)

    // *** End programmer edit section *** (Subscription CustomAttributes)
    [BusinessServer("IIS.WeatherForecast.ArchiverBS, WeatherForecast.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnDeleteFromStorage)]
    [AutoAltered()]
    [Caption("Подписка на уведомления о катаклизмах")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SubscriptionE", new string[] {
            "Cataclysm as \'Катаклизм\'",
            "Cataclysm.Name as \'Name\'",
            "Area as \'Местность\'",
            "Area.Name as \'Name\'",
            "Email as \'Email\'",
            "TimeBeforeCataclysm as \'Интервал оповещения о катаклизме\'",
            "IsArchive as \'Архивный\'"}, Hidden=new string[] {
            "Cataclysm.Name",
            "Area.Name",
            "IsArchive"})]
    [MasterViewDefineAttribute("SubscriptionE", "Cataclysm", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("SubscriptionE", "Area", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("SubscriptionL", new string[] {
            "Cataclysm.Name as \'Катаклизм\'",
            "Area.Name as \'Местность\'",
            "Email as \'Email\'",
            "TimeBeforeCataclysm as \'Интервал оповещения о катаклизме\'",
            "IsArchive as \'Архивный\'"}, Hidden=new string[] {
            "IsArchive"})]
    public class Subscription : ICSSoft.STORMNET.DataObject
    {
        
        private string fEmail;
        
        private System.DateTime fTimeBeforeCataclysm;
        
        private bool fIsArchive;
        
        private IIS.WeatherForecast.Area fArea;
        
        private IIS.WeatherForecast.Cataclysm fCataclysm;
        
        // *** Start programmer edit section *** (Subscription CustomMembers)

        // *** End programmer edit section *** (Subscription CustomMembers)

        
        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (Subscription.Email CustomAttributes)

        // *** End programmer edit section *** (Subscription.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (Subscription.Email Get start)

                // *** End programmer edit section *** (Subscription.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (Subscription.Email Get end)

                // *** End programmer edit section *** (Subscription.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscription.Email Set start)

                // *** End programmer edit section *** (Subscription.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (Subscription.Email Set end)

                // *** End programmer edit section *** (Subscription.Email Set end)
            }
        }
        
        /// <summary>
        /// TimeBeforeCataclysm.
        /// </summary>
        // *** Start programmer edit section *** (Subscription.TimeBeforeCataclysm CustomAttributes)

        // *** End programmer edit section *** (Subscription.TimeBeforeCataclysm CustomAttributes)
        public virtual System.DateTime TimeBeforeCataclysm
        {
            get
            {
                // *** Start programmer edit section *** (Subscription.TimeBeforeCataclysm Get start)

                // *** End programmer edit section *** (Subscription.TimeBeforeCataclysm Get start)
                System.DateTime result = this.fTimeBeforeCataclysm;
                // *** Start programmer edit section *** (Subscription.TimeBeforeCataclysm Get end)

                // *** End programmer edit section *** (Subscription.TimeBeforeCataclysm Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscription.TimeBeforeCataclysm Set start)

                // *** End programmer edit section *** (Subscription.TimeBeforeCataclysm Set start)
                this.fTimeBeforeCataclysm = value;
                // *** Start programmer edit section *** (Subscription.TimeBeforeCataclysm Set end)

                // *** End programmer edit section *** (Subscription.TimeBeforeCataclysm Set end)
            }
        }
        
        /// <summary>
        /// IsArchive.
        /// </summary>
        // *** Start programmer edit section *** (Subscription.IsArchive CustomAttributes)

        // *** End programmer edit section *** (Subscription.IsArchive CustomAttributes)
        public virtual bool IsArchive
        {
            get
            {
                // *** Start programmer edit section *** (Subscription.IsArchive Get start)

                // *** End programmer edit section *** (Subscription.IsArchive Get start)
                bool result = this.fIsArchive;
                // *** Start programmer edit section *** (Subscription.IsArchive Get end)

                // *** End programmer edit section *** (Subscription.IsArchive Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscription.IsArchive Set start)

                // *** End programmer edit section *** (Subscription.IsArchive Set start)
                this.fIsArchive = value;
                // *** Start programmer edit section *** (Subscription.IsArchive Set end)

                // *** End programmer edit section *** (Subscription.IsArchive Set end)
            }
        }
        
        /// <summary>
        /// Subscription.
        /// </summary>
        // *** Start programmer edit section *** (Subscription.Area CustomAttributes)

        // *** End programmer edit section *** (Subscription.Area CustomAttributes)
        [PropertyStorage(new string[] {
                "Area"})]
        [NotNull()]
        public virtual IIS.WeatherForecast.Area Area
        {
            get
            {
                // *** Start programmer edit section *** (Subscription.Area Get start)

                // *** End programmer edit section *** (Subscription.Area Get start)
                IIS.WeatherForecast.Area result = this.fArea;
                // *** Start programmer edit section *** (Subscription.Area Get end)

                // *** End programmer edit section *** (Subscription.Area Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscription.Area Set start)

                // *** End programmer edit section *** (Subscription.Area Set start)
                this.fArea = value;
                // *** Start programmer edit section *** (Subscription.Area Set end)

                // *** End programmer edit section *** (Subscription.Area Set end)
            }
        }
        
        /// <summary>
        /// Subscription.
        /// </summary>
        // *** Start programmer edit section *** (Subscription.Cataclysm CustomAttributes)

        // *** End programmer edit section *** (Subscription.Cataclysm CustomAttributes)
        [PropertyStorage(new string[] {
                "Cataclysm"})]
        [NotNull()]
        public virtual IIS.WeatherForecast.Cataclysm Cataclysm
        {
            get
            {
                // *** Start programmer edit section *** (Subscription.Cataclysm Get start)

                // *** End programmer edit section *** (Subscription.Cataclysm Get start)
                IIS.WeatherForecast.Cataclysm result = this.fCataclysm;
                // *** Start programmer edit section *** (Subscription.Cataclysm Get end)

                // *** End programmer edit section *** (Subscription.Cataclysm Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subscription.Cataclysm Set start)

                // *** End programmer edit section *** (Subscription.Cataclysm Set start)
                this.fCataclysm = value;
                // *** Start programmer edit section *** (Subscription.Cataclysm Set end)

                // *** End programmer edit section *** (Subscription.Cataclysm Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SubscriptionE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubscriptionE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubscriptionE", typeof(IIS.WeatherForecast.Subscription));
                }
            }
            
            /// <summary>
            /// "SubscriptionL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubscriptionL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubscriptionL", typeof(IIS.WeatherForecast.Subscription));
                }
            }
        }
    }
}
