//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WeatherForecast
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Wind direction.
    /// </summary>
    // *** Start programmer edit section *** (WindDirection CustomAttributes)

    // *** End programmer edit section *** (WindDirection CustomAttributes)
    public enum WindDirection
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (WindDirection.S CustomAttributes)

        // *** End programmer edit section *** (WindDirection.S CustomAttributes)
        [Caption("Ю")]
        S,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (WindDirection.SW CustomAttributes)

        // *** End programmer edit section *** (WindDirection.SW CustomAttributes)
        [Caption("ЮЗ")]
        SW,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (WindDirection.SE CustomAttributes)

        // *** End programmer edit section *** (WindDirection.SE CustomAttributes)
        [Caption("ЮВ")]
        SE,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (WindDirection.N CustomAttributes)

        // *** End programmer edit section *** (WindDirection.N CustomAttributes)
        [Caption("С")]
        N,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (WindDirection.NW CustomAttributes)

        // *** End programmer edit section *** (WindDirection.NW CustomAttributes)
        [Caption("СЗ")]
        NW,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (WindDirection.NE CustomAttributes)

        // *** End programmer edit section *** (WindDirection.NE CustomAttributes)
        [Caption("СВ")]
        NE,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (WindDirection.W CustomAttributes)

        // *** End programmer edit section *** (WindDirection.W CustomAttributes)
        [Caption("З")]
        W,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (WindDirection.E CustomAttributes)

        // *** End programmer edit section *** (WindDirection.E CustomAttributes)
        [Caption("В")]
        E,
    }
}
