//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WeatherForecast
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Archiver BS.
    /// </summary>
    // *** Start programmer edit section *** (ArchiverBS CustomAttributes)

    // *** End programmer edit section *** (ArchiverBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ArchiverBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ArchiverBS CustomMembers)

        // *** End programmer edit section *** (ArchiverBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateRegion CustomAttributes)

        // *** End programmer edit section *** (OnUpdateRegion CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateRegion(IIS.WeatherForecast.Region UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateRegion)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateRegion)
        }
        
        // *** Start programmer edit section *** (OnUpdateSubscription CustomAttributes)

        // *** End programmer edit section *** (OnUpdateSubscription CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateSubscription(IIS.WeatherForecast.Subscription UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateSubscription)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateSubscription)
        }
        
        // *** Start programmer edit section *** (OnUpdatePossibleCataclysm CustomAttributes)

        // *** End programmer edit section *** (OnUpdatePossibleCataclysm CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdatePossibleCataclysm(IIS.WeatherForecast.PossibleCataclysm UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdatePossibleCataclysm)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdatePossibleCataclysm)
        }
        
        // *** Start programmer edit section *** (OnUpdateMeteorologist CustomAttributes)

        // *** End programmer edit section *** (OnUpdateMeteorologist CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateMeteorologist(IIS.WeatherForecast.Meteorologist UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateMeteorologist)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateMeteorologist)
        }
        
        // *** Start programmer edit section *** (OnUpdateArea CustomAttributes)

        // *** End programmer edit section *** (OnUpdateArea CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateArea(IIS.WeatherForecast.Area UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateArea)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateArea)
        }
    }
}
