//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.WeatherForecast
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Day forecast BS.
    /// </summary>
    // *** Start programmer edit section *** (DayForecastBS CustomAttributes)

    // *** End programmer edit section *** (DayForecastBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class DayForecastBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (DayForecastBS CustomMembers)

        // *** End programmer edit section *** (DayForecastBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateDayForecast CustomAttributes)

        // *** End programmer edit section *** (OnUpdateDayForecast CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateDayForecast(IIS.WeatherForecast.DayForecast UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateDayForecast)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateDayForecast)
        }
    }
}
